Revert "[Qt] tst_QWebHistoryInterface::visitedLinks() fails"
This reverts commit adc47622d204163a416403abd925d2eff1817f0b.

Rolled out as it breaks the build:

../../../WebCore/css/CSSComputedStyleDeclaration.h: In member function âQString QWebElement::styleProperty(const QString&, QWebElement::StyleResolveStrategy) constâ:
../../../WebCore/css/CSSComputedStyleDeclaration.h:75: error: too many arguments to function âWTF::PassRefPtr WebCore::computedStyle(WTF::PassRefPtr)â
../../../WebKit/qt/Api/qwebelement.cpp:824: error: at this point in file